# Generated by Django 3.2.8 on 2024-03-23 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pais', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Salarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(max_length=10)),
                ('extra_jun', models.IntegerField(max_length=10)),
                ('extra_dic', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Puestos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('salario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.salarios')),
            ],
        ),
        migrations.CreateModel(
            name='Poblaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_poblacion', models.CharField(max_length=50)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paises')),
            ],
        ),
        migrations.CreateModel(
            name='Fabricas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fabrica', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('codigo_postal', models.IntegerField(max_length=10)),
                ('poblacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.poblaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('documento', models.IntegerField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('fabrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fabricas')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.puestos')),
            ],
        ),
    ]
